-- Supabase Dashboard > SQL Editor에서 전체 내용을 실행하세요.

create table if not exists public.game_rooms (
  code text primary key,
  state jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.player_accounts (
  id uuid primary key default gen_random_uuid(),
  username text not null unique,
  display_name text not null,
  password_salt text not null,
  password_hash text not null,
  score integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.account_sessions (
  token_hash text primary key,
  account_id uuid not null references public.player_accounts(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.ranked_match_results (
  id bigint generated by default as identity primary key,
  room_code text not null,
  account_id uuid not null references public.player_accounts(id) on delete cascade,
  placement smallint not null check (placement between 1 and 4),
  score_delta integer not null,
  created_at timestamptz not null default now(),
  unique(room_code, account_id)
);

create or replace function public.apply_ranked_result(
  p_room_code text,
  p_account_id uuid,
  p_placement integer,
  p_delta integer
)
returns table(new_score integer, applied boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_count integer;
begin
  insert into public.ranked_match_results(room_code, account_id, placement, score_delta)
  values (p_room_code, p_account_id, p_placement, p_delta)
  on conflict (room_code, account_id) do nothing;

  get diagnostics inserted_count = row_count;
  if inserted_count = 1 then
    update public.player_accounts
      set score = score + p_delta, updated_at = now()
      where id = p_account_id
      returning score into new_score;
    applied := true;
  else
    select score into new_score from public.player_accounts where id = p_account_id;
    applied := false;
  end if;
  return next;
end;
$$;

alter table public.game_rooms enable row level security;
alter table public.player_accounts enable row level security;
alter table public.account_sessions enable row level security;
alter table public.ranked_match_results enable row level security;

revoke all on table public.game_rooms, public.player_accounts, public.account_sessions, public.ranked_match_results from anon, authenticated;
grant select, insert, update, delete on table public.game_rooms, public.player_accounts, public.account_sessions, public.ranked_match_results to service_role;
revoke all on function public.apply_ranked_result(text, uuid, integer, integer) from public, anon, authenticated;
grant execute on function public.apply_ranked_result(text, uuid, integer, integer) to service_role;

create index if not exists game_rooms_updated_at_idx on public.game_rooms (updated_at);
create index if not exists account_sessions_account_idx on public.account_sessions (account_id);
create index if not exists account_sessions_expires_idx on public.account_sessions (expires_at);
create index if not exists ranked_match_results_account_idx on public.ranked_match_results (account_id, created_at desc);
