-- Supabase Dashboard > SQL Editor에서 전체 내용을 실행하세요.

create table if not exists public.game_rooms (
  code text primary key,
  state jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.player_accounts (
  id uuid primary key default gen_random_uuid(),
  username text not null unique,
  display_name text not null,
  password_salt text not null,
  password_hash text not null,
  score integer not null default 0,
  signal_points integer not null default 0,
  relic_inventory jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- score는 랭크 점수(RP)로 사용합니다. 기존 점수는 그대로 RP로 전환됩니다.
alter table public.player_accounts add column if not exists signal_points integer not null default 0;
alter table public.player_accounts add column if not exists relic_inventory jsonb not null default '{}'::jsonb;

-- 기존 음수 RP·재화를 복구하고 앞으로도 0 아래로 내려가지 않게 합니다.
update public.player_accounts
set score = 0, updated_at = now()
where score < 0;

alter table public.player_accounts
drop constraint if exists player_accounts_score_nonnegative;

alter table public.player_accounts
add constraint player_accounts_score_nonnegative check (score >= 0);

update public.player_accounts set signal_points = 0, updated_at = now() where signal_points < 0;
alter table public.player_accounts drop constraint if exists player_accounts_signal_points_nonnegative;
alter table public.player_accounts add constraint player_accounts_signal_points_nonnegative check (signal_points >= 0);

create table if not exists public.account_sessions (
  token_hash text primary key,
  account_id uuid not null references public.player_accounts(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.ranked_match_results (
  id bigint generated by default as identity primary key,
  room_code text not null,
  account_id uuid not null references public.player_accounts(id) on delete cascade,
  placement smallint not null check (placement between 1 and 4),
  score_delta integer not null,
  points_reward integer not null default 0,
  created_at timestamptz not null default now(),
  unique(room_code, account_id)
);

alter table public.ranked_match_results add column if not exists points_reward integer not null default 0;

drop function if exists public.apply_ranked_result(text, uuid, integer, integer);
create or replace function public.apply_ranked_result(
  p_room_code text,
  p_account_id uuid,
  p_placement integer,
  p_delta integer,
  p_points integer
)
returns table(new_score integer, new_points integer, applied boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_count integer;
begin
  insert into public.ranked_match_results(room_code, account_id, placement, score_delta, points_reward)
  values (p_room_code, p_account_id, p_placement, p_delta, greatest(0, p_points))
  on conflict (room_code, account_id) do nothing;

  get diagnostics inserted_count = row_count;
  if inserted_count = 1 then
    update public.player_accounts
      set score = greatest(0, score + p_delta), signal_points = signal_points + greatest(0, p_points), updated_at = now()
      where id = p_account_id
      returning score, signal_points into new_score, new_points;
    applied := true;
  else
    select score, signal_points into new_score, new_points from public.player_accounts where id = p_account_id;
    applied := false;
  end if;
  return next;
end;
$$;

drop function if exists public.apply_relic_draw(uuid, integer, jsonb);
create or replace function public.apply_relic_draw(
  p_account_id uuid,
  p_cost integer,
  p_results jsonb
)
returns table(new_points integer, new_inventory jsonb)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_points integer;
  inventory jsonb;
  relic_id text;
  amount_text text;
  amount integer;
begin
  if p_cost not in (160, 1600) then
    raise exception 'invalid relic draw cost';
  end if;

  select signal_points, coalesce(relic_inventory, '{}'::jsonb)
    into current_points, inventory
    from public.player_accounts
    where id = p_account_id
    for update;

  if not found or current_points < p_cost then
    return;
  end if;

  for relic_id, amount_text in select key, value from jsonb_each_text(coalesce(p_results, '{}'::jsonb))
  loop
    amount := greatest(0, amount_text::integer);
    if amount > 0 then
      inventory := jsonb_set(
        inventory,
        array[relic_id],
        to_jsonb(coalesce((inventory ->> relic_id)::integer, 0) + amount),
        true
      );
    end if;
  end loop;

  update public.player_accounts
    set signal_points = signal_points - p_cost,
        relic_inventory = inventory,
        updated_at = now()
    where id = p_account_id
    returning signal_points, relic_inventory into new_points, new_inventory;
  return next;
end;
$$;

alter table public.game_rooms enable row level security;
alter table public.player_accounts enable row level security;
alter table public.account_sessions enable row level security;
alter table public.ranked_match_results enable row level security;

revoke all on table public.game_rooms, public.player_accounts, public.account_sessions, public.ranked_match_results from anon, authenticated;
grant select, insert, update, delete on table public.game_rooms, public.player_accounts, public.account_sessions, public.ranked_match_results to service_role;
revoke all on function public.apply_ranked_result(text, uuid, integer, integer, integer) from public, anon, authenticated;
grant execute on function public.apply_ranked_result(text, uuid, integer, integer, integer) to service_role;
revoke all on function public.apply_relic_draw(uuid, integer, jsonb) from public, anon, authenticated;
grant execute on function public.apply_relic_draw(uuid, integer, jsonb) to service_role;

create index if not exists game_rooms_updated_at_idx on public.game_rooms (updated_at);
create index if not exists account_sessions_account_idx on public.account_sessions (account_id);
create index if not exists account_sessions_expires_idx on public.account_sessions (expires_at);
create index if not exists ranked_match_results_account_idx on public.ranked_match_results (account_id, created_at desc);
